name: Publish GraphTools
on:
  release:
    types:
    - published

jobs:
  publish:
    name: publish
    runs-on: windows-latest
    steps:
    - name: checkout module repo
      uses: actions/checkout@v3

    - name: Build module
      shell: pwsh
      run: |
        ./Build.ps1 -InstallDependencies -Build -Publish -GalleryToken $env:PSGALLERY_TOKEN

      env:
        PSGALLERY_TOKEN: ${{ secrets.PSGALLERY_TOKEN }}  # This is sourced from your GHA secrets